// Shrine puzzles rendered as DOM/SVG overlays. Each puzzle is generated by applying
// random *legal* moves to a solved state, which guarantees it is always solvable.

const RUNES = ['ᚠ', 'ᚱ', 'ᛉ', 'ᛟ', 'ᚦ', 'ᛗ', 'ᛞ', 'ᚨ'];
const RUNE_PITCH = [392, 440, 523.25, 587.33, 659.25, 783.99];
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

export class PuzzleUI {
  constructor(audio) {
    this.audio = audio;
    this.el = document.getElementById('puzzle');
    this.active = null;
  }

  get isOpen() { return !!this.active; }

  open(shrineDef, onSolved, onClose) {
    this.close(false);
    const token = {};
    this.active = token;
    this.onSolved = onSolved;
    this.onClose = onClose;
    const color = '#' + shrineDef.color.toString(16).padStart(6, '0');
    this.el.style.setProperty('--shrine', color);
    this.el.innerHTML = `
      <div class="puzzle-card">
        <div class="puzzle-head">
          <div class="eyebrow">${shrineDef.eyebrow || `Rune Shrine · Trial ${shrineDef.difficulty > 1 ? 'of Mastery' : 'of Insight'}`}</div>
          <h2>${shrineDef.name}</h2>
          <p class="intro">${shrineDef.intro}</p>
        </div>
        <div class="puzzle-board"></div>
        <div class="puzzle-status" aria-live="polite"></div>
        <div class="puzzle-actions">
          <button class="btn ghost" data-act="reset">Reset</button>
          <button class="btn" data-act="leave">${shrineDef.eyebrow ? 'Step away' : 'Leave shrine'} <kbd>Esc</kbd></button>
        </div>
      </div>`;
    this.el.classList.add('show');
    this.board = this.el.querySelector('.puzzle-board');
    this.status = this.el.querySelector('.puzzle-status');
    this.el.querySelector('[data-act=leave]').onclick = () => this.close();
    const resetBtn = this.el.querySelector('[data-act=reset]');
    // Every puzzle kind is a method named after it (school puzzles are installed from puzzles-schools.js).
    this[shrineDef.puzzle].call(this, shrineDef.difficulty, token, resetBtn);
  }

  close(fireCallback = true) {
    if (this.keyHandler) { removeEventListener('keydown', this.keyHandler); this.keyHandler = null; }
    if (!this.active) return;
    this.active = null;
    this.el.classList.remove('show');
    this.el.innerHTML = '';
    if (fireCallback) this.onClose?.();
  }

  solved(token) {
    if (this.active !== token) return;
    if (this.keyHandler) { removeEventListener('keydown', this.keyHandler); this.keyHandler = null; }
    this.audio.play('solve');
    this.status.innerHTML = '<span class="win">The shrine awakens! An Arcane Sigil forms in your hand.</span>';
    this.board.classList.add('solved');
    setTimeout(() => {
      if (this.active !== token) return;
      this.active = null;
      this.el.classList.remove('show');
      this.el.innerHTML = '';
      this.onSolved?.();
    }, 1800);
  }

  // ---------- 1. Echoing Runes (Simon-style memory) ----------
  sequence(difficulty, token, resetBtn) {
    resetBtn.style.display = 'none';
    const rounds = difficulty > 1 ? [5, 6, 7] : [3, 4, 5];
    const speed = difficulty > 1 ? 430 : 620;
    const seq = [];
    for (let i = 0; i < rounds[rounds.length - 1]; i++) seq.push(Math.floor(Math.random() * 6));
    this.board.innerHTML = `
      <div class="rune-wheel">
        ${RUNES.slice(0, 6).map((r, i) => `<button class="rune" data-i="${i}" style="--a:${i * 60}deg" disabled>${r}</button>`).join('')}
        <div class="rune-core"><div class="round-pips">${rounds.map(() => '<i></i>').join('')}</div></div>
      </div>`;
    const btns = [...this.board.querySelectorAll('.rune')];
    const pips = [...this.board.querySelectorAll('.round-pips i')];
    let round = 0, input = [], accepting = false;

    const flash = async (i, ms) => {
      btns[i].classList.add('lit');
      this.audio.tone(RUNE_PITCH[i], ms / 1000 + 0.2, { vol: 0.12, type: 'triangle' });
      await sleep(ms);
      btns[i].classList.remove('lit');
    };
    const playRound = async () => {
      accepting = false;
      btns.forEach((b) => (b.disabled = true));
      this.status.textContent = 'Listen to the runes…';
      await sleep(700);
      for (let k = 0; k < rounds[round]; k++) {
        if (this.active !== token) return;
        await flash(seq[k], speed);
        await sleep(speed * 0.35);
      }
      if (this.active !== token) return;
      input = [];
      accepting = true;
      btns.forEach((b) => (b.disabled = false));
      this.status.textContent = `Echo the melody (${rounds[round]} runes)`;
    };
    btns.forEach((b) => {
      b.onclick = async () => {
        if (!accepting) return;
        const i = +b.dataset.i;
        flash(i, 220);
        input.push(i);
        const k = input.length - 1;
        if (input[k] !== seq[k]) {
          accepting = false;
          this.audio.play('error');
          this.board.classList.add('shake');
          setTimeout(() => this.board.classList.remove('shake'), 400);
          this.status.innerHTML = '<span class="bad">The runes fall silent. Listen again…</span>';
          await sleep(900);
          playRound();
          return;
        }
        if (input.length === rounds[round]) {
          accepting = false;
          pips[round].classList.add('on');
          round++;
          if (round >= rounds.length) return this.solved(token);
          this.status.textContent = 'Yes… the song grows longer.';
          await sleep(700);
          playRound();
        }
      };
    });
    playRound();
  }

  // ---------- 2. Ley-Line Nexus (lights-out) ----------
  lights(difficulty, token, resetBtn) {
    const N = 5;
    const grid = new Array(N * N).fill(true);
    const toggle = (g, i) => {
      const x = i % N, y = Math.floor(i / N);
      [[0, 0], [1, 0], [-1, 0], [0, 1], [0, -1]].forEach(([dx, dy]) => {
        const nx = x + dx, ny = y + dy;
        if (nx >= 0 && nx < N && ny >= 0 && ny < N) g[ny * N + nx] = !g[ny * N + nx];
      });
    };
    const presses = new Set();
    const target = 5 + difficulty * 3;
    while (presses.size < target) presses.add(Math.floor(Math.random() * N * N));
    presses.forEach((i) => toggle(grid, i));
    const start = grid.slice();
    let moves = 0;
    this.board.innerHTML = `<div class="ley-grid" style="--n:${N}">${grid.map((_, i) => `<button class="ley" data-i="${i}" aria-label="Ley node ${i + 1}"></button>`).join('')}</div>`;
    const cells = [...this.board.querySelectorAll('.ley')];
    const render = () => {
      cells.forEach((c, i) => c.classList.toggle('on', grid[i]));
      const lit = grid.filter(Boolean).length;
      this.status.textContent = `${lit} / ${N * N} nodes awakened · ${moves} moves`;
    };
    cells.forEach((c) => {
      c.onclick = () => {
        if (this.active !== token) return;
        toggle(grid, +c.dataset.i);
        moves++;
        this.audio.tone(300 + grid.filter(Boolean).length * 25, 0.25, { vol: 0.08, type: 'triangle' });
        c.classList.add('pulse'); setTimeout(() => c.classList.remove('pulse'), 300);
        render();
        if (grid.every(Boolean)) { cells.forEach((x) => (x.disabled = true)); this.solved(token); }
      };
    });
    resetBtn.onclick = () => { start.forEach((v, i) => (grid[i] = v)); moves = 0; this.audio.play('ui'); render(); };
    render();
  }

  // ---------- 3. Astral Lock (coupled rotating rings) ----------
  rings(difficulty, token, resetBtn) {
    const R = difficulty > 1 ? 4 : 3, S = 8;
    const off = new Array(R).fill(0);
    // Turning ring i also turns its outer neighbour the opposite way (wrapping on mastery).
    const move = (o, i, d) => {
      o[i] = (o[i] + d + S) % S;
      const j = difficulty > 1 ? (i + 1) % R : i + 1;
      if (j < R && j !== i) o[j] = (o[j] - d + S) % S;
    };
    do {
      for (let k = 0; k < 10 + difficulty * 8; k++) move(off, Math.floor(Math.random() * R), Math.random() < 0.5 ? 1 : -1);
    } while (off.every((v) => v === 0));
    const start = off.slice();
    let moves = 0;
    const size = 360, cx = size / 2;
    const radii = Array.from({ length: R }, (_, i) => 52 + i * (118 / R) * 1.05);
    const star = (x, y, r, cls) => {
      let d = '';
      for (let k = 0; k < 10; k++) {
        const a = (k / 10) * Math.PI * 2 - Math.PI / 2, rr = k % 2 ? r * 0.45 : r;
        d += (k ? 'L' : 'M') + (x + Math.cos(a) * rr).toFixed(1) + ' ' + (y + Math.sin(a) * rr).toFixed(1);
      }
      return `<path class="${cls}" d="${d}Z"/>`;
    };
    const ringsSvg = radii.map((r, i) => {
      const glyphs = Array.from({ length: S }, (_, k) => {
        const a = (k / S) * Math.PI * 2 - Math.PI / 2;
        const x = cx + Math.cos(a) * r, y = cx + Math.sin(a) * r;
        return k === 0 ? star(x, y, 11, 'key') : `<text x="${x}" y="${y}" class="glyph">${RUNES[(k + i) % RUNES.length]}</text>`;
      }).join('');
      return `<g class="ring" data-r="${i}" style="transform-origin:${cx}px ${cx}px">
        <circle cx="${cx}" cy="${cx}" r="${r}" class="track"/>${glyphs}</g>`;
    }).join('');
    const controls = radii.map((_, i) => `
      <div class="ring-ctl"><span>${['Inner', 'Middle', 'Outer', 'Crown'][i] || 'Ring'} ring${R === 4 && i === 2 ? '' : ''}</span>
        <button class="btn sm" data-r="${i}" data-d="-1" aria-label="Turn ring ${i + 1} counter-clockwise">⟲</button>
        <button class="btn sm" data-r="${i}" data-d="1" aria-label="Turn ring ${i + 1} clockwise">⟳</button></div>`).join('');
    this.board.innerHTML = `
      <div class="astral">
        <svg viewBox="0 0 ${size} ${size}" class="astral-svg">
          <defs><radialGradient id="ag"><stop offset="0" stop-color="var(--shrine)" stop-opacity=".35"/><stop offset="1" stop-color="var(--shrine)" stop-opacity="0"/></radialGradient></defs>
          <circle cx="${cx}" cy="${cx}" r="${cx - 4}" fill="url(#ag)"/>
          <path d="M${cx - 10} 6 L${cx + 10} 6 L${cx} 22Z" class="north"/>
          <line x1="${cx}" y1="22" x2="${cx}" y2="${cx - 30}" class="north-line"/>
          ${ringsSvg}
          <circle cx="${cx}" cy="${cx}" r="24" class="hub"/>
        </svg>
        <div class="ring-controls">${controls}
          <p class="hint">${difficulty > 1 ? 'Each ring drags the next one backward — and the crown drags the inner ring.' : 'Turning a ring also turns the ring outside it, in reverse.'}</p>
        </div>
      </div>`;
    const groups = [...this.board.querySelectorAll('.ring')];
    const turns = new Array(R).fill(0); // unbounded for smooth CSS rotation
    const render = () => {
      groups.forEach((g, i) => {
        g.style.transform = `rotate(${turns[i] * (360 / S)}deg)`;
        g.classList.toggle('aligned', off[i] === 0);
      });
      const n = off.filter((v) => v === 0).length;
      this.status.textContent = `${n} / ${R} stars point north · ${moves} moves`;
    };
    // Visual turns track offsets exactly; initialise from scramble.
    off.forEach((v, i) => (turns[i] = v));
    const btns = [...this.board.querySelectorAll('.ring-ctl button')];
    btns.forEach((b) => {
      b.onclick = () => {
        if (this.active !== token) return;
        const i = +b.dataset.r, d = +b.dataset.d;
        const before = off.slice();
        move(off, i, d);
        off.forEach((v, k) => {
          let delta = v - before[k];
          if (delta > S / 2) delta -= S; if (delta < -S / 2) delta += S;
          turns[k] += delta;
        });
        moves++;
        this.audio.play('rune');
        render();
        if (off.every((v) => v === 0)) { btns.forEach((x) => (x.disabled = true)); this.solved(token); }
      };
    });
    resetBtn.onclick = () => {
      start.forEach((v, i) => { off[i] = v; turns[i] = v; });
      moves = 0; this.audio.play('ui'); render();
    };
    render();
  }
}
